/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace sg.protocol.user
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Attendance : TBase
  {
    private long _i_LastAttendanceDate;
    private int _i_AttendanceCount;

    public long I_LastAttendanceDate
    {
      get
      {
        return _i_LastAttendanceDate;
      }
      set
      {
        __isset.i_LastAttendanceDate = true;
        this._i_LastAttendanceDate = value;
      }
    }

    public int I_AttendanceCount
    {
      get
      {
        return _i_AttendanceCount;
      }
      set
      {
        __isset.i_AttendanceCount = true;
        this._i_AttendanceCount = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool i_LastAttendanceDate;
      public bool i_AttendanceCount;
    }

    public Attendance() {
      this._i_LastAttendanceDate = 0;
      this.__isset.i_LastAttendanceDate = true;
      this._i_AttendanceCount = 0;
      this.__isset.i_AttendanceCount = true;
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              I_LastAttendanceDate = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              I_AttendanceCount = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Attendance");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.i_LastAttendanceDate) {
        field.Name = "i_LastAttendanceDate";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(I_LastAttendanceDate);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_AttendanceCount) {
        field.Name = "i_AttendanceCount";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_AttendanceCount);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Attendance(");
      sb.Append("I_LastAttendanceDate: ");
      sb.Append(I_LastAttendanceDate);
      sb.Append(",I_AttendanceCount: ");
      sb.Append(I_AttendanceCount);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
