/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace sg.protocol.user
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class UserEquipment : TBase
  {
    private int _i_EquipmentSeq;
    private int _i_EquipmentId;
    private bool _b_IsNew;
    private int _i_PlayerSeq;

    public int I_EquipmentSeq
    {
      get
      {
        return _i_EquipmentSeq;
      }
      set
      {
        __isset.i_EquipmentSeq = true;
        this._i_EquipmentSeq = value;
      }
    }

    public int I_EquipmentId
    {
      get
      {
        return _i_EquipmentId;
      }
      set
      {
        __isset.i_EquipmentId = true;
        this._i_EquipmentId = value;
      }
    }

    public bool B_IsNew
    {
      get
      {
        return _b_IsNew;
      }
      set
      {
        __isset.b_IsNew = true;
        this._b_IsNew = value;
      }
    }

    public int I_PlayerSeq
    {
      get
      {
        return _i_PlayerSeq;
      }
      set
      {
        __isset.i_PlayerSeq = true;
        this._i_PlayerSeq = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool i_EquipmentSeq;
      public bool i_EquipmentId;
      public bool b_IsNew;
      public bool i_PlayerSeq;
    }

    public UserEquipment() {
      this._i_EquipmentSeq = 0;
      this.__isset.i_EquipmentSeq = true;
      this._i_EquipmentId = 0;
      this.__isset.i_EquipmentId = true;
      this._b_IsNew = false;
      this.__isset.b_IsNew = true;
      this._i_PlayerSeq = 0;
      this.__isset.i_PlayerSeq = true;
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              I_EquipmentSeq = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              I_EquipmentId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Bool) {
              B_IsNew = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              I_PlayerSeq = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("UserEquipment");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.i_EquipmentSeq) {
        field.Name = "i_EquipmentSeq";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_EquipmentSeq);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_EquipmentId) {
        field.Name = "i_EquipmentId";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_EquipmentId);
        oprot.WriteFieldEnd();
      }
      if (__isset.b_IsNew) {
        field.Name = "b_IsNew";
        field.Type = TType.Bool;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(B_IsNew);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_PlayerSeq) {
        field.Name = "i_PlayerSeq";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_PlayerSeq);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("UserEquipment(");
      sb.Append("I_EquipmentSeq: ");
      sb.Append(I_EquipmentSeq);
      sb.Append(",I_EquipmentId: ");
      sb.Append(I_EquipmentId);
      sb.Append(",B_IsNew: ");
      sb.Append(B_IsNew);
      sb.Append(",I_PlayerSeq: ");
      sb.Append(I_PlayerSeq);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
