/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace sg.protocol.user
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class UserItem : TBase
  {
    private int _i_ItemSeq;
    private int _i_ItemId;
    private int _i_ItemQuantity;

    public int I_ItemSeq
    {
      get
      {
        return _i_ItemSeq;
      }
      set
      {
        __isset.i_ItemSeq = true;
        this._i_ItemSeq = value;
      }
    }

    public int I_ItemId
    {
      get
      {
        return _i_ItemId;
      }
      set
      {
        __isset.i_ItemId = true;
        this._i_ItemId = value;
      }
    }

    public int I_ItemQuantity
    {
      get
      {
        return _i_ItemQuantity;
      }
      set
      {
        __isset.i_ItemQuantity = true;
        this._i_ItemQuantity = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool i_ItemSeq;
      public bool i_ItemId;
      public bool i_ItemQuantity;
    }

    public UserItem() {
      this._i_ItemSeq = 0;
      this.__isset.i_ItemSeq = true;
      this._i_ItemId = 0;
      this.__isset.i_ItemId = true;
      this._i_ItemQuantity = 0;
      this.__isset.i_ItemQuantity = true;
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              I_ItemSeq = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              I_ItemId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              I_ItemQuantity = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("UserItem");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.i_ItemSeq) {
        field.Name = "i_ItemSeq";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_ItemSeq);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_ItemId) {
        field.Name = "i_ItemId";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_ItemId);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_ItemQuantity) {
        field.Name = "i_ItemQuantity";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_ItemQuantity);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("UserItem(");
      sb.Append("I_ItemSeq: ");
      sb.Append(I_ItemSeq);
      sb.Append(",I_ItemId: ");
      sb.Append(I_ItemId);
      sb.Append(",I_ItemQuantity: ");
      sb.Append(I_ItemQuantity);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
