/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace sg.protocol.user
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class UserAlarm : TBase
  {
    private int _i_ConnectReward;
    private int _i_Post;

    public int I_ConnectReward
    {
      get
      {
        return _i_ConnectReward;
      }
      set
      {
        __isset.i_ConnectReward = true;
        this._i_ConnectReward = value;
      }
    }

    public int I_Post
    {
      get
      {
        return _i_Post;
      }
      set
      {
        __isset.i_Post = true;
        this._i_Post = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool i_ConnectReward;
      public bool i_Post;
    }

    public UserAlarm() {
      this._i_ConnectReward = 0;
      this.__isset.i_ConnectReward = true;
      this._i_Post = 0;
      this.__isset.i_Post = true;
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              I_ConnectReward = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              I_Post = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("UserAlarm");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.i_ConnectReward) {
        field.Name = "i_ConnectReward";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_ConnectReward);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_Post) {
        field.Name = "i_Post";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_Post);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("UserAlarm(");
      sb.Append("I_ConnectReward: ");
      sb.Append(I_ConnectReward);
      sb.Append(",I_Post: ");
      sb.Append(I_Post);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
