/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;

namespace sg.protocol.error
{
  public static class errorConstants
  {
    public static int kTimeOut = 1;
    public static int kInvalidMessageFormat = 2;
    public static int kInvalidArgument = 3;
    public static int kSgGameSystemGeneral = 4;
    public static int kHttpError = 5;
    public static int kDBError = 6;
    public static int koAuthError = 7;
    public static int kParameterError = 8;
    public static int kXignCodeError = 9;
    public static int kDuplicateCallApi = 10;
    public static int kDuplicateCallGameRecordApi = 11;
    public static int kAreadyProcessApi = 12;
    public static int kLittleOverAgain = 13;
    public static int kEmptyData = 100;
    public static int kNotExistUser = 101;
    public static int kNotSupportMembership = 102;
    public static int kMembershipAuthServerBusy = 103;
    public static int kPPMembershipAuthFail = 104;
    public static int kDuplicateTeamName = 105;
    public static int kProcessingFailure = 106;
    public static int kDuplicateLogin = 107;
    public static int kBlockUser = 108;
    public static int kSessionExpireUser = 109;
    public static int kRedisKeyExpire = 110;
    public static int kMergeAccount = 111;
    public static int kAlreadyGiveItem = 601;
    public static int kAlreadyGivePromotionItem = 602;
    public static int kMaxReceiveBuy = 603;
    public static int kFailPurchaseAuth = 604;
    public static int kInvalidCoupon = 701;
    public static int kExpiredCoupon = 702;
    public static int kAlreadyCoupon = 703;
    public static int kMaxReceiveCoupon = 704;
    public static int kInspectionStart = 888;
    public static int kHaveMaxFriend = 901;
    public static int kAlreadyFriend = 902;
    public static int kNotAddFriend = 903;
    public static int kNotSearchFriend = 904;
    public static int kNotAddMe = 905;
    public static int kAlreadyRequestFriend = 906;
    public static int kAlreadyRecvFriend = 907;
    public static int kLimitFriendShipPoint = 908;
    public static int kSystemString1030002 = 1030002;
    public static int kSystemString1030004 = 1030004;
    public static Dictionary<int, string> MAP_CONST = new Dictionary<int, string>();
    static errorConstants()
    {
      MAP_CONST[2] = "잘못된메세지포멧입니다";
      MAP_CONST[4] = "서버 내부 오류";
      MAP_CONST[5] = "Http 프로토콜 오류";
      MAP_CONST[1] = "타임아웃";
      MAP_CONST[3] = "잘못된인자값입니다.";
      MAP_CONST[9] = "XignCode 오류";
      MAP_CONST[12] = "처리된 API 호출";
      MAP_CONST[101] = "존재하지 않는 사용자";
      MAP_CONST[102] = "지원되지 않는 멤버십 유형";
      MAP_CONST[103] = "멤버십 인증 서버가 응답하지 않습니다";
      MAP_CONST[6] = "DB 구문 오류";
      MAP_CONST[10] = "API 중복 호출 오류";
      MAP_CONST[13] = "나중에 다시 보내기 요청";
      MAP_CONST[100] = "데이터가 없음";
      MAP_CONST[104] = "PmangPlus 회원 인증 실패";
      MAP_CONST[7] = "인증 오류";
      MAP_CONST[11] = "게임 결과 API 반복 호출 오류";
      MAP_CONST[604] = "결제 검증 실패";
      MAP_CONST[105] = "중복 팀 이름";
      MAP_CONST[109] = "게임 실행 후 24시간 후에 로그인 정보가 업데이트되고 타이틀이 업데이트됩니다.";
      MAP_CONST[602] = "프로모션 항목 전송됨";
      MAP_CONST[603] = "한 번만 구입할 수 있습니다.";
      MAP_CONST[703] = "사용한 이벤트 일련 번호입니다.";
      MAP_CONST[111] = "Merge 처리된 계정입니다.";
      MAP_CONST[704] = "사용된 이벤트 일련 번호입니다.";
      MAP_CONST[110] = "세션이 만료되었으며 제목으로 업데이트됩니다.";
      MAP_CONST[702] = "이 이벤트의 일련 번호가 사용 기간을 초과했습니다";
      MAP_CONST[108] = "플레이어 차단";
      MAP_CONST[107] = "중복 로그인 플레이어";
      MAP_CONST[601] = "결제 처리됨";
      MAP_CONST[106] = "처리 실패";
      MAP_CONST[701] = "일련 번호가 없습니다. 입력한 일련 번호가 올바른지 확인하십시오.";
      MAP_CONST[905] = "나를 친구로 초대할 수 없습니다";
      MAP_CONST[902] = "이미 친구";
      MAP_CONST[888] = "점검으로 인하여 게임이 종료됩니다.";
      MAP_CONST[906] = "친구 초대가 전송되었습니다";
      MAP_CONST[903] = "친구를 더 추가할 수 없습니다";
      MAP_CONST[908] = "매일 보내는 우정 포인트 초과";
      MAP_CONST[901] = "파트너의 친구 목록이 가득 찼습니다.";
      MAP_CONST[904] = "그런 팀 이름이 없습니다.";
      MAP_CONST[907] = "상대방이 친구 초대 상태를 보냈습니다.";
      MAP_CONST[1030002] = "팀 이름에 사용할 수 없는 단어가 포함되어 있습니다.";
      MAP_CONST[1030004] = "닉네임이 같은 플레이어";
    }
  }
}
