/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace sg.protocol.common
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Attendance : TBase
  {
    private int _i_Day;
    private int _i_RewardType;
    private int _i_RewardId;
    private int _i_RewardCount;

    public int I_Day
    {
      get
      {
        return _i_Day;
      }
      set
      {
        __isset.i_Day = true;
        this._i_Day = value;
      }
    }

    public int I_RewardType
    {
      get
      {
        return _i_RewardType;
      }
      set
      {
        __isset.i_RewardType = true;
        this._i_RewardType = value;
      }
    }

    public int I_RewardId
    {
      get
      {
        return _i_RewardId;
      }
      set
      {
        __isset.i_RewardId = true;
        this._i_RewardId = value;
      }
    }

    public int I_RewardCount
    {
      get
      {
        return _i_RewardCount;
      }
      set
      {
        __isset.i_RewardCount = true;
        this._i_RewardCount = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool i_Day;
      public bool i_RewardType;
      public bool i_RewardId;
      public bool i_RewardCount;
    }

    public Attendance() {
      this._i_Day = 0;
      this.__isset.i_Day = true;
      this._i_RewardType = 0;
      this.__isset.i_RewardType = true;
      this._i_RewardId = 0;
      this.__isset.i_RewardId = true;
      this._i_RewardCount = 0;
      this.__isset.i_RewardCount = true;
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              I_Day = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              I_RewardType = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              I_RewardId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              I_RewardCount = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Attendance");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.i_Day) {
        field.Name = "i_Day";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_Day);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_RewardType) {
        field.Name = "i_RewardType";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_RewardType);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_RewardId) {
        field.Name = "i_RewardId";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_RewardId);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_RewardCount) {
        field.Name = "i_RewardCount";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_RewardCount);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Attendance(");
      sb.Append("I_Day: ");
      sb.Append(I_Day);
      sb.Append(",I_RewardType: ");
      sb.Append(I_RewardType);
      sb.Append(",I_RewardId: ");
      sb.Append(I_RewardId);
      sb.Append(",I_RewardCount: ");
      sb.Append(I_RewardCount);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
