/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace sg.protocol.common
{
  public enum KLeaveReason
  {
    kGeneral = 1,
    kUserReq = 2,
    kTimeOut = 3,
    kNetDisconnect = 4,
    kOperatorCommand = 5,
  }
}
