/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace sg.protocol.common
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ShopPackageGoods : TBase
  {
    private int _i_Id;
    private int _i_ProductType;
    private int _i_ProductId;
    private int _i_ProductCount;

    public int I_Id
    {
      get
      {
        return _i_Id;
      }
      set
      {
        __isset.i_Id = true;
        this._i_Id = value;
      }
    }

    public int I_ProductType
    {
      get
      {
        return _i_ProductType;
      }
      set
      {
        __isset.i_ProductType = true;
        this._i_ProductType = value;
      }
    }

    public int I_ProductId
    {
      get
      {
        return _i_ProductId;
      }
      set
      {
        __isset.i_ProductId = true;
        this._i_ProductId = value;
      }
    }

    public int I_ProductCount
    {
      get
      {
        return _i_ProductCount;
      }
      set
      {
        __isset.i_ProductCount = true;
        this._i_ProductCount = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool i_Id;
      public bool i_ProductType;
      public bool i_ProductId;
      public bool i_ProductCount;
    }

    public ShopPackageGoods() {
      this._i_Id = 0;
      this.__isset.i_Id = true;
      this._i_ProductType = 0;
      this.__isset.i_ProductType = true;
      this._i_ProductId = 0;
      this.__isset.i_ProductId = true;
      this._i_ProductCount = 0;
      this.__isset.i_ProductCount = true;
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              I_Id = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              I_ProductType = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              I_ProductId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              I_ProductCount = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ShopPackageGoods");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.i_Id) {
        field.Name = "i_Id";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_Id);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_ProductType) {
        field.Name = "i_ProductType";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_ProductType);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_ProductId) {
        field.Name = "i_ProductId";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_ProductId);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_ProductCount) {
        field.Name = "i_ProductCount";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_ProductCount);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ShopPackageGoods(");
      sb.Append("I_Id: ");
      sb.Append(I_Id);
      sb.Append(",I_ProductType: ");
      sb.Append(I_ProductType);
      sb.Append(",I_ProductId: ");
      sb.Append(I_ProductId);
      sb.Append(",I_ProductCount: ");
      sb.Append(I_ProductCount);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
