/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace sg.protocol.msg_web_api
{
  public enum eGameMode
  {
    None = 0,
  }
}
