/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace sg.protocol.msg_web_api
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MsgAnsUserInfoFastOfflineReward : TBase
  {
    private sg.protocol.basic.Error _error;
    private int _i_RewardGold;
    private int _i_RewardId_1;
    private int _i_RewardCount_1;
    private int _i_RewardId_2;
    private int _i_RewardCount_2;
    private int _i_RewardId_3;
    private int _i_RewardCount_3;
    private int _i_FastGetPrice;

    public sg.protocol.basic.Error Error
    {
      get
      {
        return _error;
      }
      set
      {
        __isset.error = true;
        this._error = value;
      }
    }

    public int I_RewardGold
    {
      get
      {
        return _i_RewardGold;
      }
      set
      {
        __isset.i_RewardGold = true;
        this._i_RewardGold = value;
      }
    }

    public int I_RewardId_1
    {
      get
      {
        return _i_RewardId_1;
      }
      set
      {
        __isset.i_RewardId_1 = true;
        this._i_RewardId_1 = value;
      }
    }

    public int I_RewardCount_1
    {
      get
      {
        return _i_RewardCount_1;
      }
      set
      {
        __isset.i_RewardCount_1 = true;
        this._i_RewardCount_1 = value;
      }
    }

    public int I_RewardId_2
    {
      get
      {
        return _i_RewardId_2;
      }
      set
      {
        __isset.i_RewardId_2 = true;
        this._i_RewardId_2 = value;
      }
    }

    public int I_RewardCount_2
    {
      get
      {
        return _i_RewardCount_2;
      }
      set
      {
        __isset.i_RewardCount_2 = true;
        this._i_RewardCount_2 = value;
      }
    }

    public int I_RewardId_3
    {
      get
      {
        return _i_RewardId_3;
      }
      set
      {
        __isset.i_RewardId_3 = true;
        this._i_RewardId_3 = value;
      }
    }

    public int I_RewardCount_3
    {
      get
      {
        return _i_RewardCount_3;
      }
      set
      {
        __isset.i_RewardCount_3 = true;
        this._i_RewardCount_3 = value;
      }
    }

    public int I_FastGetPrice
    {
      get
      {
        return _i_FastGetPrice;
      }
      set
      {
        __isset.i_FastGetPrice = true;
        this._i_FastGetPrice = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool error;
      public bool i_RewardGold;
      public bool i_RewardId_1;
      public bool i_RewardCount_1;
      public bool i_RewardId_2;
      public bool i_RewardCount_2;
      public bool i_RewardId_3;
      public bool i_RewardCount_3;
      public bool i_FastGetPrice;
    }

    public MsgAnsUserInfoFastOfflineReward() {
      this._i_RewardGold = 0;
      this.__isset.i_RewardGold = true;
      this._i_RewardId_1 = 0;
      this.__isset.i_RewardId_1 = true;
      this._i_RewardCount_1 = 0;
      this.__isset.i_RewardCount_1 = true;
      this._i_RewardId_2 = 0;
      this.__isset.i_RewardId_2 = true;
      this._i_RewardCount_2 = 0;
      this.__isset.i_RewardCount_2 = true;
      this._i_RewardId_3 = 0;
      this.__isset.i_RewardId_3 = true;
      this._i_RewardCount_3 = 0;
      this.__isset.i_RewardCount_3 = true;
      this._i_FastGetPrice = 0;
      this.__isset.i_FastGetPrice = true;
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Error = new sg.protocol.basic.Error();
              Error.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              I_RewardGold = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              I_RewardId_1 = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              I_RewardCount_1 = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.I32) {
              I_RewardId_2 = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I32) {
              I_RewardCount_2 = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.I32) {
              I_RewardId_3 = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.I32) {
              I_RewardCount_3 = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 9:
            if (field.Type == TType.I32) {
              I_FastGetPrice = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("MsgAnsUserInfoFastOfflineReward");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Error != null && __isset.error) {
        field.Name = "error";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        Error.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_RewardGold) {
        field.Name = "i_RewardGold";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_RewardGold);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_RewardId_1) {
        field.Name = "i_RewardId_1";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_RewardId_1);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_RewardCount_1) {
        field.Name = "i_RewardCount_1";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_RewardCount_1);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_RewardId_2) {
        field.Name = "i_RewardId_2";
        field.Type = TType.I32;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_RewardId_2);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_RewardCount_2) {
        field.Name = "i_RewardCount_2";
        field.Type = TType.I32;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_RewardCount_2);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_RewardId_3) {
        field.Name = "i_RewardId_3";
        field.Type = TType.I32;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_RewardId_3);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_RewardCount_3) {
        field.Name = "i_RewardCount_3";
        field.Type = TType.I32;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_RewardCount_3);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_FastGetPrice) {
        field.Name = "i_FastGetPrice";
        field.Type = TType.I32;
        field.ID = 9;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_FastGetPrice);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("MsgAnsUserInfoFastOfflineReward(");
      sb.Append("Error: ");
      sb.Append(Error== null ? "<null>" : Error.ToString());
      sb.Append(",I_RewardGold: ");
      sb.Append(I_RewardGold);
      sb.Append(",I_RewardId_1: ");
      sb.Append(I_RewardId_1);
      sb.Append(",I_RewardCount_1: ");
      sb.Append(I_RewardCount_1);
      sb.Append(",I_RewardId_2: ");
      sb.Append(I_RewardId_2);
      sb.Append(",I_RewardCount_2: ");
      sb.Append(I_RewardCount_2);
      sb.Append(",I_RewardId_3: ");
      sb.Append(I_RewardId_3);
      sb.Append(",I_RewardCount_3: ");
      sb.Append(I_RewardCount_3);
      sb.Append(",I_FastGetPrice: ");
      sb.Append(I_FastGetPrice);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
