/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace sg.protocol.msg_web_api
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MsgAnsTeamDeck : TBase
  {
    private sg.protocol.basic.Error _error;
    private Dictionary<int, sg.protocol.user.UserTeamDeck> _m_UserTeamDeck;
    private Dictionary<int, sg.protocol.user.UserRuneDeck> _m_UserRuneDeck;
    private Dictionary<int, sg.protocol.user.UserBoosterDeck> _m_UserBoosterDeck;

    public sg.protocol.basic.Error Error
    {
      get
      {
        return _error;
      }
      set
      {
        __isset.error = true;
        this._error = value;
      }
    }

    public Dictionary<int, sg.protocol.user.UserTeamDeck> M_UserTeamDeck
    {
      get
      {
        return _m_UserTeamDeck;
      }
      set
      {
        __isset.m_UserTeamDeck = true;
        this._m_UserTeamDeck = value;
      }
    }

    public Dictionary<int, sg.protocol.user.UserRuneDeck> M_UserRuneDeck
    {
      get
      {
        return _m_UserRuneDeck;
      }
      set
      {
        __isset.m_UserRuneDeck = true;
        this._m_UserRuneDeck = value;
      }
    }

    public Dictionary<int, sg.protocol.user.UserBoosterDeck> M_UserBoosterDeck
    {
      get
      {
        return _m_UserBoosterDeck;
      }
      set
      {
        __isset.m_UserBoosterDeck = true;
        this._m_UserBoosterDeck = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool error;
      public bool m_UserTeamDeck;
      public bool m_UserRuneDeck;
      public bool m_UserBoosterDeck;
    }

    public MsgAnsTeamDeck() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Error = new sg.protocol.basic.Error();
              Error.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Map) {
              {
                M_UserTeamDeck = new Dictionary<int, sg.protocol.user.UserTeamDeck>();
                TMap _map0 = iprot.ReadMapBegin();
                for( int _i1 = 0; _i1 < _map0.Count; ++_i1)
                {
                  int _key2;
                  sg.protocol.user.UserTeamDeck _val3;
                  _key2 = iprot.ReadI32();
                  _val3 = new sg.protocol.user.UserTeamDeck();
                  _val3.Read(iprot);
                  M_UserTeamDeck[_key2] = _val3;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Map) {
              {
                M_UserRuneDeck = new Dictionary<int, sg.protocol.user.UserRuneDeck>();
                TMap _map4 = iprot.ReadMapBegin();
                for( int _i5 = 0; _i5 < _map4.Count; ++_i5)
                {
                  int _key6;
                  sg.protocol.user.UserRuneDeck _val7;
                  _key6 = iprot.ReadI32();
                  _val7 = new sg.protocol.user.UserRuneDeck();
                  _val7.Read(iprot);
                  M_UserRuneDeck[_key6] = _val7;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Map) {
              {
                M_UserBoosterDeck = new Dictionary<int, sg.protocol.user.UserBoosterDeck>();
                TMap _map8 = iprot.ReadMapBegin();
                for( int _i9 = 0; _i9 < _map8.Count; ++_i9)
                {
                  int _key10;
                  sg.protocol.user.UserBoosterDeck _val11;
                  _key10 = iprot.ReadI32();
                  _val11 = new sg.protocol.user.UserBoosterDeck();
                  _val11.Read(iprot);
                  M_UserBoosterDeck[_key10] = _val11;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("MsgAnsTeamDeck");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Error != null && __isset.error) {
        field.Name = "error";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        Error.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (M_UserTeamDeck != null && __isset.m_UserTeamDeck) {
        field.Name = "m_UserTeamDeck";
        field.Type = TType.Map;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, M_UserTeamDeck.Count));
          foreach (int _iter12 in M_UserTeamDeck.Keys)
          {
            oprot.WriteI32(_iter12);
            M_UserTeamDeck[_iter12].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (M_UserRuneDeck != null && __isset.m_UserRuneDeck) {
        field.Name = "m_UserRuneDeck";
        field.Type = TType.Map;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, M_UserRuneDeck.Count));
          foreach (int _iter13 in M_UserRuneDeck.Keys)
          {
            oprot.WriteI32(_iter13);
            M_UserRuneDeck[_iter13].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (M_UserBoosterDeck != null && __isset.m_UserBoosterDeck) {
        field.Name = "m_UserBoosterDeck";
        field.Type = TType.Map;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, M_UserBoosterDeck.Count));
          foreach (int _iter14 in M_UserBoosterDeck.Keys)
          {
            oprot.WriteI32(_iter14);
            M_UserBoosterDeck[_iter14].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("MsgAnsTeamDeck(");
      sb.Append("Error: ");
      sb.Append(Error== null ? "<null>" : Error.ToString());
      sb.Append(",M_UserTeamDeck: ");
      sb.Append(M_UserTeamDeck);
      sb.Append(",M_UserRuneDeck: ");
      sb.Append(M_UserRuneDeck);
      sb.Append(",M_UserBoosterDeck: ");
      sb.Append(M_UserBoosterDeck);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
