/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace sg.protocol.msg_web_api
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MsgAnsGetEventStageList : TBase
  {
    private sg.protocol.basic.Error _error;
    private Dictionary<int, sg.protocol.common.EventStageList> _m_EventStageList;

    public sg.protocol.basic.Error Error
    {
      get
      {
        return _error;
      }
      set
      {
        __isset.error = true;
        this._error = value;
      }
    }

    public Dictionary<int, sg.protocol.common.EventStageList> M_EventStageList
    {
      get
      {
        return _m_EventStageList;
      }
      set
      {
        __isset.m_EventStageList = true;
        this._m_EventStageList = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool error;
      public bool m_EventStageList;
    }

    public MsgAnsGetEventStageList() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Error = new sg.protocol.basic.Error();
              Error.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Map) {
              {
                M_EventStageList = new Dictionary<int, sg.protocol.common.EventStageList>();
                TMap _map135 = iprot.ReadMapBegin();
                for( int _i136 = 0; _i136 < _map135.Count; ++_i136)
                {
                  int _key137;
                  sg.protocol.common.EventStageList _val138;
                  _key137 = iprot.ReadI32();
                  _val138 = new sg.protocol.common.EventStageList();
                  _val138.Read(iprot);
                  M_EventStageList[_key137] = _val138;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("MsgAnsGetEventStageList");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Error != null && __isset.error) {
        field.Name = "error";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        Error.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (M_EventStageList != null && __isset.m_EventStageList) {
        field.Name = "m_EventStageList";
        field.Type = TType.Map;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, M_EventStageList.Count));
          foreach (int _iter139 in M_EventStageList.Keys)
          {
            oprot.WriteI32(_iter139);
            M_EventStageList[_iter139].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("MsgAnsGetEventStageList(");
      sb.Append("Error: ");
      sb.Append(Error== null ? "<null>" : Error.ToString());
      sb.Append(",M_EventStageList: ");
      sb.Append(M_EventStageList);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
