/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace sg.protocol.msg_web_api
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MsgAnsMainData : TBase
  {
    private sg.protocol.basic.Error _error;
    private sg.protocol.user.UserInfoBasic _st_UserInfoBasic;
    private sg.protocol.user.UserAssets _st_UserAssets;
    private sg.protocol.user.UserAlarm _st_UserAlarm;

    public sg.protocol.basic.Error Error
    {
      get
      {
        return _error;
      }
      set
      {
        __isset.error = true;
        this._error = value;
      }
    }

    public sg.protocol.user.UserInfoBasic St_UserInfoBasic
    {
      get
      {
        return _st_UserInfoBasic;
      }
      set
      {
        __isset.st_UserInfoBasic = true;
        this._st_UserInfoBasic = value;
      }
    }

    public sg.protocol.user.UserAssets St_UserAssets
    {
      get
      {
        return _st_UserAssets;
      }
      set
      {
        __isset.st_UserAssets = true;
        this._st_UserAssets = value;
      }
    }

    public sg.protocol.user.UserAlarm St_UserAlarm
    {
      get
      {
        return _st_UserAlarm;
      }
      set
      {
        __isset.st_UserAlarm = true;
        this._st_UserAlarm = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool error;
      public bool st_UserInfoBasic;
      public bool st_UserAssets;
      public bool st_UserAlarm;
    }

    public MsgAnsMainData() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Error = new sg.protocol.basic.Error();
              Error.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              St_UserInfoBasic = new sg.protocol.user.UserInfoBasic();
              St_UserInfoBasic.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              St_UserAssets = new sg.protocol.user.UserAssets();
              St_UserAssets.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Struct) {
              St_UserAlarm = new sg.protocol.user.UserAlarm();
              St_UserAlarm.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("MsgAnsMainData");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Error != null && __isset.error) {
        field.Name = "error";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        Error.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (St_UserInfoBasic != null && __isset.st_UserInfoBasic) {
        field.Name = "st_UserInfoBasic";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        St_UserInfoBasic.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (St_UserAssets != null && __isset.st_UserAssets) {
        field.Name = "st_UserAssets";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        St_UserAssets.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (St_UserAlarm != null && __isset.st_UserAlarm) {
        field.Name = "st_UserAlarm";
        field.Type = TType.Struct;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        St_UserAlarm.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("MsgAnsMainData(");
      sb.Append("Error: ");
      sb.Append(Error== null ? "<null>" : Error.ToString());
      sb.Append(",St_UserInfoBasic: ");
      sb.Append(St_UserInfoBasic== null ? "<null>" : St_UserInfoBasic.ToString());
      sb.Append(",St_UserAssets: ");
      sb.Append(St_UserAssets== null ? "<null>" : St_UserAssets.ToString());
      sb.Append(",St_UserAlarm: ");
      sb.Append(St_UserAlarm== null ? "<null>" : St_UserAlarm.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
