/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace sg.protocol.msg_web_api
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MsgReqSetRuneDeck : TBase
  {
    private long _uid;
    private int _i_DeckId;
    private int _i_Slot0RuneId;
    private int _i_Slot1RuneId;
    private int _i_Slot2RuneId;
    private int _i_Slot3RuneId;
    private int _i_Slot4RuneId;
    private string _s_DeckName;

    public long Uid
    {
      get
      {
        return _uid;
      }
      set
      {
        __isset.uid = true;
        this._uid = value;
      }
    }

    public int I_DeckId
    {
      get
      {
        return _i_DeckId;
      }
      set
      {
        __isset.i_DeckId = true;
        this._i_DeckId = value;
      }
    }

    public int I_Slot0RuneId
    {
      get
      {
        return _i_Slot0RuneId;
      }
      set
      {
        __isset.i_Slot0RuneId = true;
        this._i_Slot0RuneId = value;
      }
    }

    public int I_Slot1RuneId
    {
      get
      {
        return _i_Slot1RuneId;
      }
      set
      {
        __isset.i_Slot1RuneId = true;
        this._i_Slot1RuneId = value;
      }
    }

    public int I_Slot2RuneId
    {
      get
      {
        return _i_Slot2RuneId;
      }
      set
      {
        __isset.i_Slot2RuneId = true;
        this._i_Slot2RuneId = value;
      }
    }

    public int I_Slot3RuneId
    {
      get
      {
        return _i_Slot3RuneId;
      }
      set
      {
        __isset.i_Slot3RuneId = true;
        this._i_Slot3RuneId = value;
      }
    }

    public int I_Slot4RuneId
    {
      get
      {
        return _i_Slot4RuneId;
      }
      set
      {
        __isset.i_Slot4RuneId = true;
        this._i_Slot4RuneId = value;
      }
    }

    public string S_DeckName
    {
      get
      {
        return _s_DeckName;
      }
      set
      {
        __isset.s_DeckName = true;
        this._s_DeckName = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool uid;
      public bool i_DeckId;
      public bool i_Slot0RuneId;
      public bool i_Slot1RuneId;
      public bool i_Slot2RuneId;
      public bool i_Slot3RuneId;
      public bool i_Slot4RuneId;
      public bool s_DeckName;
    }

    public MsgReqSetRuneDeck() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              Uid = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              I_DeckId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              I_Slot0RuneId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              I_Slot1RuneId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.I32) {
              I_Slot2RuneId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I32) {
              I_Slot3RuneId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.I32) {
              I_Slot4RuneId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.String) {
              S_DeckName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("MsgReqSetRuneDeck");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.uid) {
        field.Name = "uid";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Uid);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_DeckId) {
        field.Name = "i_DeckId";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_DeckId);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_Slot0RuneId) {
        field.Name = "i_Slot0RuneId";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_Slot0RuneId);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_Slot1RuneId) {
        field.Name = "i_Slot1RuneId";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_Slot1RuneId);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_Slot2RuneId) {
        field.Name = "i_Slot2RuneId";
        field.Type = TType.I32;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_Slot2RuneId);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_Slot3RuneId) {
        field.Name = "i_Slot3RuneId";
        field.Type = TType.I32;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_Slot3RuneId);
        oprot.WriteFieldEnd();
      }
      if (__isset.i_Slot4RuneId) {
        field.Name = "i_Slot4RuneId";
        field.Type = TType.I32;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(I_Slot4RuneId);
        oprot.WriteFieldEnd();
      }
      if (S_DeckName != null && __isset.s_DeckName) {
        field.Name = "s_DeckName";
        field.Type = TType.String;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(S_DeckName);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("MsgReqSetRuneDeck(");
      sb.Append("Uid: ");
      sb.Append(Uid);
      sb.Append(",I_DeckId: ");
      sb.Append(I_DeckId);
      sb.Append(",I_Slot0RuneId: ");
      sb.Append(I_Slot0RuneId);
      sb.Append(",I_Slot1RuneId: ");
      sb.Append(I_Slot1RuneId);
      sb.Append(",I_Slot2RuneId: ");
      sb.Append(I_Slot2RuneId);
      sb.Append(",I_Slot3RuneId: ");
      sb.Append(I_Slot3RuneId);
      sb.Append(",I_Slot4RuneId: ");
      sb.Append(I_Slot4RuneId);
      sb.Append(",S_DeckName: ");
      sb.Append(S_DeckName);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
